### PR TITLE
list_app_keys extension naming fixed

### LINKED ISSUE #92: list_app_keys naming issue
list_app_keys extension expects `'3scale-options': 'list_app_keys=1'` header in the request headers. Due to a naming issue in the threescalers package , invalid extension name is added to the header. (`app_keys_list` instead of `list_app_keys`).

### PR DESCRIPTION
**Pull request by NomadXD**
This PR fixes the list_app_keys extension naming issue inside threescalers. Fixes #92

### CODE REVIEW

**Review by unleashed — CHANGES_REQUESTED** [review]
@NomadXD let's also change the name of the enum so it is named the same as the extension to avoid potentially confusing the user

**Comment by NomadXD** [comment]
@unleashed fixed the enum variant name to ListAppKeys.

**Review by unleashed — APPROVED** [review]

**Comment by unleashed** [comment]
@NomadXD looks like the checks now work, but before we merge: can you fix the clippy issue (probably as a result of using a new version of the toolchain, as it's unlikely you created it), squash both commits (since they are small and essentially doing one thing) and change commit titles so they have a format like `area or file: add/introduce/fix feature/bugfix/etc`? In this case something like `extensions: fix incorrect spelling of list_app_keys feature`.

**Pull request merged**
